name: Use Hello Action 2

on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Greeting from Hello Action 2
        uses: ./.github/actions/eas/action2