name: Matrix Build & Fancy Summary

on:
    push:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize]

jobs:
  build:
    name: build-${{ matrix.platform }}-${{ matrix.app }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ios, android]
        app: [AppA, AppB, AppC, AppD]

    steps:
    - name: Simulate build
      run: |
        if [[ "${{ matrix.app }}" == "AppB" && "${{ matrix.platform }}" == "ios" ]]; then
          status="fail"
        else
          status="success"
        fi

        echo "{\"platform\": \"${{ matrix.platform }}\", \"app\": \"${{ matrix.app }}\", \"status\": \"$status\"}" > result.json

    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: result-${{ matrix.platform }}-${{ matrix.app }}
        path: result.json

  summary:
    name: Generate Fancy Summary
    runs-on: ubuntu-latest
    needs: build
    if: always()

    steps:
    - name: Download all build results
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Merge results and generate HTML
      run: |
        echo "<style>
        table {border-collapse: collapse; width: 100%;}
        th, td {border: 1px solid #ddd; padding: 8px;}
        th {background-color: #f2f2f2;}
        td {text-align: center;}
        </style>" > summary.html

        echo "<h2>Build Summary</h2>" >> summary.html
        echo "<table>" >> summary.html
        echo "<tr><th>Platform</th><th>App</th><th>Status</th></tr>" >> summary.html

        for file in artifacts/**/result.json; do
          platform=$(jq -r '.platform' "$file")
          app=$(jq -r '.app' "$file")
          status=$(jq -r '.status' "$file")

          if [[ "$status" == "success" ]]; then
            icon="✅"
          elif [[ "$status" == "fail" ]]; then
            icon="❌"
          else
            icon="❓"
          fi

          echo "<tr><td>$platform</td><td>$app</td><td>$icon $status</td></tr>" >> summary.html
        done

        echo "</table>" >> summary.html

    - name: Append HTML to GitHub Step Summary
      run: cat summary.html >> $GITHUB_STEP_SUMMARY

    - name: Create PR comment if run from PR
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        edit-mode: replace
        body: |
            <!-- build-summary -->
            <h2>Build Summary</h2>

            $(cat summary.html)
