name: Matrix Build & Fancy Summary
permissions:
  pull-requests: write  # for PR comments
  contents: read        # always safe to have this

on:
    push:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ios, android]
        app: [AppA, AppB, AppC, AppD]
    name: Build ${{ matrix.app }} - ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate QR & result
        run: |
          mkdir output
          echo "Dummy QR for ${{ matrix.app }} ${{ matrix.platform }}" > output/qr-${{ matrix.app }}-${{ matrix.platform }}.png
          echo "{ \"status\": \"success\", \"link\": \"https://example.com/${{ matrix.app }}/${{ matrix.platform }}\" }" > output/result-${{ matrix.app }}-${{ matrix.platform }}.json

      - uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.app }}-${{ matrix.platform }}
          path: output/*


  summary:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - uses: actions/download-artifact@v4

      - name: Generate HTML Summary
        run: |
          echo "<h2>Build Summary</h2>" > summary.html
          echo "<table border=1 cellspacing=0 cellpadding=5>" >> summary.html
          echo "<tr><th></th><th>iOS</th><th>Android</th></tr>" >> summary.html

          for app in AppA AppB AppC AppD; do
            echo "<tr><th>$app</th>" >> summary.html
            for platform in ios android; do
              ART=result-${app}-${platform}
              LINK=$(jq -r .link $ART/result-${app}-${platform}.json)
              STATUS=$(jq -r .status $ART/result-${app}-${platform}.json)
              BADGE="https://img.shields.io/badge/${STATUS}-${STATUS == success && "green" || "red"}"
              echo "<td><img src='${LINK}/qr.png' width=100><br><a href='${LINK}'>Download</a><br><img src='${BADGE}'></td>" >> summary.html
            done
            echo "</tr>" >> summary.html
          done

          echo "</table>" >> summary.html

      - name: Upload summary.html artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-summary
          path: summary.html

      - name: Add to GitHub Summary
        run: cat summary.html >> $GITHUB_STEP_SUMMARY

      - name: Create or Update PR Comment
        if: github.event.pull_request
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <!-- build-summary -->
            $(cat summary.html)